- packages/eslint-config/__tests__/test.spec.ts
- packages/eslint-config/__tests__/typescript.bad.ts
- packages/eslint-config/__tests__/typescript.good.ts
- packages/eslint-config/index.js
BREAKING CHANGES: after upgrade your build will failed
> feat(eslint-config): add no-useless-constructor

- packages/eslint-config/__tests__/test.spec.ts
- packages/eslint-config/__tests__/typescript.bad.ts
- packages/eslint-config/__tests__/typescript.good.ts
- packages/eslint-config/index.js
BREAKING CHANGES: after update build failed
> feat: don't declare non-const enums

- packages/eslint-config/__tests__/test.spec.ts
- packages/eslint-config/__tests__/typescript.bad.ts
- packages/eslint-config/__tests__/typescript.good.ts
- packages/eslint-config/index.js
BREAKING CHANGES: after update build failed
> feat: strict pascal case for Enum

- README.md
- packages/common/README.md
- packages/common/angular.json
- packages/common/integration/tests/common-types.spec.ts
- packages/common/integration/tests/setupJest.ts
- packages/common/integration/tests/tsconfig.spec.json
- packages/common/jest.config.js
- packages/common/ng-package.json
- packages/common/package.json
- packages/common/src/common.module.ts
- packages/common/src/public_api.ts
- packages/common/tsconfig.json
- packages/common/tsconfig.lib.json
- packages/common/typings/package.json
- packages/common/typings/src/any.ts
- packages/common/typings/src/class-type.ts
- packages/common/typings/src/descriptor.ts
- packages/common/typings/src/immutability.ts
- packages/common/typings/src/plaing-object-of.ts
- packages/common/typings/src/public_api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/common): integration with LernaJS

- packages/common/date/src/serial-date.ts
- packages/common/integration/tests/serial-date.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(@angular-ru/common): use unified signature for SerialDate

- packages/flex-layout/integration/app/assets/github.min.css
- packages/flex-layout/integration/app/assets/hljs.js
- packages/flex-layout/integration/app/custom-theme.scss
- packages/flex-layout/integration/app/index.html
- packages/flex-layout/integration/app/src/app-routing.module.ts
- packages/flex-layout/integration/app/src/app.component.html
- packages/flex-layout/integration/app/src/app.module.ts
- packages/flex-layout/integration/app/src/samples/guide/guide.component.html
- packages/flex-layout/integration/app/src/samples/guide/guide.component.ts
- packages/flex-layout/integration/app/src/samples/guide/guide.module.ts
- packages/flex-layout/integration/app/src/samples/sample-first/sample-first.component.html
- packages/flex-layout/integration/app/src/samples/sample-first/sample-first.component.scss
- packages/flex-layout/integration/app/src/samples/sample-first/sample-first.component.ts
- packages/flex-layout/integration/app/src/samples/sample-first/sample-first.module.ts
- packages/flex-layout/integration/app/styles.scss
- packages/flex-layout/package.json
- packages/flex-layout/styles/shared.scss
```
[x ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
```
[ ] Yes
[ ] No
```
> Flex layouts/app

- packages/common/docs/string.md
- packages/common/integration/tests/string/string.spec.ts
- packages/common/string/src/public_api.ts
- packages/common/string/src/trim.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/string): add trim

- packages/common/form/src/directives/amount-format/amount-format.directive.ts
- packages/common/form/src/directives/amount-format/amount-format.module.ts
- packages/common/form/src/directives/convert-case/convert-case.directive.ts
- packages/common/form/src/directives/convert-case/convert-case.module.ts
- packages/common/form/src/directives/max-length/max-length.directive.ts
- packages/common/form/src/directives/max-length/max-length.module.ts
- packages/common/form/src/directives/trim-input/trim-input.directive.ts
- packages/common/form/src/directives/trim-input/trim-input.module.ts
- packages/common/form/src/public_api.ts
- packages/common/integration/tests/form/amount-format.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feature(@angular-ru/common): add form extensions

- packages/common/tooltip/package.json
- packages/common/tooltip/src/public_api.ts
- packages/common/tooltip/src/tooltip.directive.ts
- packages/common/tooltip/src/tooltip.interface.ts
- packages/common/tooltip/src/tooltip.module.ts
- packages/common/tooltip/src/tooltip.properties.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/common): add tooltip

- CHANGELOG.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore(): fix changelog

- packages/tooltip/ng-package.json
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(): fix package for export styles

- packages/common/form/src/directives/disable-control/disable-control.directive.ts
- packages/common/form/src/directives/disable-control/disable-control.module.ts
- packages/common/form/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add disable-control directive

- README.md
- packages/commitlint-config/package.json
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(build-config): add missing publishConfig in package.json

- packages/commitlint-config/index.js
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(commitlint-config): disable subject-case rule

- packages/build-tools/package.json
- packages/common/tsconfig.lib.json
- packages/ng-table-builder/tsconfig.lib.json
- packages/stream/tsconfig.lib.json
- yarn.lock
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: upgrade to new ng-packagr

- packages/common/docs/utils.md
- packages/common/utils/src/check-value-is-filled.ts
- packages/common/utils/src/public_api.ts
- packages/ng-table-builder/integration/tests/services/utils.service.spec.ts
-  [ ] Bugfix
-  [x] Feature
-  [ ] Code style update (formatting, local variables)
-  [ ] Refactoring (no functional changes, no api changes)
-  [ ] Build related changes
-  [ ] CI related changes
-  [ ] Documentation content changes
-  [ ] Other... Please describe:
-  [ ] Yes
-  [x] No
> feat(@angular-ru/common): add checkValueIsFilled function

- packages/common/array/src/is-filled-list.ts
- packages/common/array/src/public_api.ts
- packages/common/docs/array.md
- packages/common/integration/tests/array/utility-arrays.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add isFilledList method

- packages/common/array/src/exclude.ts
- packages/common/array/src/public_api.ts
- packages/common/docs/array.md
- packages/common/integration/tests/array/utility-arrays.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add exclude array function

- packages/renovate-config/README.md
- packages/renovate-config/package.json
- renovate.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/renovate-config): add renovate preset package

- .github/workflows/workflow.yml
- packages/eslint-config/package.json
- yarn.lock
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(@angular-ru/eslint-config): remove codelyzer from dependency

- packages/common/docs/directives.md
- packages/common/docs/forms.md
- packages/common/forms/package.json
- packages/common/forms/src/control-value-accessor-patcher.ts
- packages/common/forms/src/control-value-interceptor-descriptor.interface.ts
- packages/common/forms/src/control-value-interceptor.ts
- packages/common/forms/src/public_api.ts
- packages/common/integration/tests/forms/helpers/sync-control-directives.ts
- packages/common/integration/tests/forms/sync-control-value-interceptor.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add ControlValueInterceptor service

- packages/flex-layout/src/directives/flex-container.directive.ts
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```
> refactor(flex-layout): support string type for flex-container

- packages/common/docs/validators.md
- packages/common/integration/tests/validators/date-interval-validator.spec.ts
- packages/common/integration/tests/validators/date-limit-validator.spec.ts
- packages/common/validators/src/date-interval.validator.ts
- packages/common/validators/src/limit-date.validator.ts
- packages/common/validators/src/public_api.ts
- packages/common/validators/src/utils/assert-form-group.ts
- packages/common/validators/src/utils/get-date-interval.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add date & interval limit validators

- .gitignore
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor: update .gitignore

- packages/http/tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(@angular-ru/http): correct resolve artifacts in tsconfig.json

- .github/workflows/workflow.yml
- package.json
- packages/common/package.json
- packages/common/symlink.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: use symlink only common package

- packages/common/docs/validators.md
- packages/common/integration/tests/validators/date-interval-validator.spec.ts
- packages/common/integration/tests/validators/ordered-interval-validator.spec.ts
- packages/common/validators/src/date-interval.validator.ts
- packages/common/validators/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Added an interval validator that checks the order of endpoints. The beginning must always be less than or equal to the end.
```
[ ] Yes
[x] No
```
> feat: added validator for ordered interval

- packages/common/typings/src/public_api.ts
- packages/common/typings/src/string-values-of-enum.ts
- packages/ng-table-builder/integration/tests/components/table-builder.component.spec.ts
- packages/ng-table-builder/src/public_api.ts
- packages/ng-table-builder/src/services/sortable/sortable.service.ts
- packages/ng-table-builder/src/table-builder.api.ts
- packages/ng-table-builder/src/table-builder.component.ts
- packages/ng-table-builder/src/types/table-sort-types.type.ts
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/ng-table-builder): add type for SortTypes input

- packages/common/integration/tests/validators/multi-validators.spec.ts
- packages/common/integration/tests/validators/required-some-value-by-keys-validator.spec.ts
- packages/common/validators/src/required-some-value-by-keys.validator.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor: added tests for validators

- packages/ng-table-builder/integration/tests/components/table-builder.component.spec.ts
- packages/ng-table-builder/integration/tests/services/selection.service.spec.ts
- packages/ng-table-builder/src/services/selection/selection.service.ts
- packages/ng-table-builder/src/table-builder.api.ts
- packages/ng-table-builder/src/table-builder.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(@angular-ru/ng-table-builder): update rows in selection after sort or filter

- packages/ng-table-builder/src/components/ngx-context-menu/ngx-context-menu.component.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(@angular-ru/ng-table-builder): fixed a bug in the context menu for Chrome v.67

- packages/common/date/src/date-range.interface.ts
- packages/common/date/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add DateRange interface

- packages/common/decorators/package.json
- packages/common/decorators/src/attribute-boolean.ts
- packages/common/decorators/src/public_api.ts
- packages/common/docs/decorators.md
- packages/common/integration/tests/decorators/attribute-boolean.spec.ts
- packages/common/typings/src/input-boolean.ts
- packages/common/typings/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add decorator AttributeBoolean

- packages/common/directives/src/public_api.ts
- packages/common/directives/src/split-string/split-string-options.interface.ts
- packages/common/directives/src/split-string/split-string.directive.ts
- packages/common/directives/src/split-string/split-string.module.ts
- packages/common/docs/directives.md
- packages/common/integration/tests/directives/split-string.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add SplitString directive

- packages/common/array/src/public_api.ts
- packages/common/array/src/unique.ts
- packages/common/docs/array.md
- packages/common/integration/tests/array/unique.spec.ts
- packages/common/integration/tests/date/end-of-day.spec.ts
- packages/common/integration/tests/date/shift-date.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat: added util for filtering array 'unique'

- packages/common/docs/typings.md
- packages/common/typings/src/keys-of-type.ts
- packages/common/typings/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add KeysOfType type function

- packages/common/docs/pipes.md
- packages/common/integration/tests/pipes/filter-unique.pipe.spec.ts
- packages/common/pipes/src/filter-unique/filter-unique-pipe.module.ts
- packages/common/pipes/src/filter-unique/filter-unique.pipe.ts
- packages/common/pipes/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
> feat(@angular-ru/common): add FilterUniquePipe

- packages/common/docs/typings.md
- packages/common/typings/src/ng-css-classes.ts
- packages/common/typings/src/public_api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/common): add NgCssClasses

- packages/common/array/src/exclude.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(@angular-ru/common): fix exclude typings

- packages/common/docs/pipes.md
- packages/common/pipes/src/public_api.ts
- packages/common/pipes/src/type-as/type-as-pipe.module.ts
- packages/common/pipes/src/type-as/type-as.pipe.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add TypeAs pipe

- packages/common/docs/typings.md
- packages/common/typings/src/date-interval-descriptor.ts
- packages/common/typings/src/public_api.ts
- packages/common/validators/src/date-interval.validator.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add DateIntervalDescriptor

- packages/ng-table-builder/integration/app/tsconfig.app.json
- packages/ng-table-builder/integration/tests/components/selection-mock.component.spec.ts
- packages/ng-table-builder/integration/tests/helpers/mock-web-worker.service.ts
- packages/ng-table-builder/src/abstract-table-builder-api.directive.ts
- packages/ng-table-builder/src/services/selection/selection.service.ts
- packages/ng-table-builder/src/table-builder.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(@angular-ru/ng-table-builder): fix selection items with shift key

- packages/common/array/src/include.ts
- packages/common/array/src/public_api.ts
- packages/common/docs/array.md
- packages/common/integration/tests/array/include.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat: added util 'include'

- packages/common/array/src/has-at-most-one-item.ts
- packages/common/array/src/has-items.ts
- packages/common/array/src/has-many-items.ts
- packages/common/array/src/has-no-items.ts
- packages/common/array/src/has-one-item.ts
- packages/common/array/src/is-empty-list.ts
- packages/common/array/src/is-filled-list.ts
- packages/common/array/src/is-multiple-list.ts
- packages/common/array/src/is-single-list.ts
- packages/common/array/src/public_api.ts
- packages/common/docs/array.md
- packages/common/docs/pipes.md
- packages/common/integration/tests/array/utility-arrays.spec.ts
- packages/common/integration/tests/pipes/at-pipe.spec.ts
- packages/common/pipes/src/at/at-pipe.module.ts
- packages/common/pipes/src/at/at.pipe.ts
- packages/common/pipes/src/has-at-most-one-item/has-at-most-one-item-pipe.module.ts
- packages/common/pipes/src/has-at-most-one-item/has-at-most-one-item.pipe.ts
- packages/common/pipes/src/has-items/has-items-pipe.module.ts
- packages/common/pipes/src/has-items/has-items.pipe.ts
- packages/common/pipes/src/has-many-items/has-many-items-pipe.module.ts
- packages/common/pipes/src/has-many-items/has-many-items.pipe.ts
- packages/common/pipes/src/has-no-items/has-no-items-pipe.module.ts
- packages/common/pipes/src/has-no-items/has-no-items.pipe.ts
- packages/common/pipes/src/has-one-item/has-one-item-pipe.module.ts
- packages/common/pipes/src/has-one-item/has-one-item.pipe.ts
- packages/common/pipes/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add has-items array utils

- packages/common/integration/tests/validators/date-interval-validator.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(@angular-ru/common): fix test on max interval validator

- packages/common/class-transformer/src/public_api.ts
- packages/common/class-transformer/src/transform-to-boolean.ts
- packages/common/docs/class-transformer.md
- packages/common/integration/tests/class-transformer/class-transformer.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add transformToBoolean function

- .husky/pre-commit
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: don't use `git add .` before commit files

- packages/common/docs/string.md
- packages/common/integration/tests/string/string.spec.ts
- packages/common/string/src/get-count-spaces-on-string.ts
- packages/common/string/src/get-first-symbol.ts
- packages/common/string/src/get-last-symbol.ts
- packages/common/string/src/public_api.ts
- packages/common/string/src/remove-last-symbol.ts
- packages/common/string/src/remove-non-numeric-symbols.ts
- packages/common/string/src/replace-every-comma-on-dot.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/common): add new string utils

- packages/renovate-config/package.json
- renovate.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/renovate-config): update group lists

- packages/websocket/integration/tests/clients/websocket-client.spec.ts
- packages/websocket/integration/tests/setup-jest.ts
- packages/websocket/integration/tests/tsconfig.spec.json
- packages/websocket/jest.config.js
- packages/websocket/package.json
- packages/websocket/src/abstract-websocket.client.ts
...and provide serialize & deserialize methods to override
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(@angular-ru/websocket): close socket connection on error & serializers

- BREAKING_CHANGES.md
- packages/common/integration/tests/object/object.spec.ts
- packages/common/object/src/deep-clone.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/common): change deepClone signature

- packages/common/docs/pipes.md
- packages/common/integration/tests/nodejs/ts-utils.spec.ts
- packages/common/integration/tests/pipes/number-format.spec.ts
- packages/common/pipes/src/number-format/number-format.pipe.ts
- packages/common/tsconfig.base.json
- packages/common/tsconfig.json
- packages/common/tsconfig.lib.json
- packages/common/tsconfig.spec.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build(@angular-ru/common): refactoring tsconfig.json

- packages/renovate-config/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/renovate-config): add jasmine / karma sections

- packages/renovate-config/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/renovate-config): fix regexp

- .github/CODEOWNERS
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: add @schirbak as codeowner

- packages/eslint-config/index.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/eslint-config): add no-dupe-class-members

- packages/renovate-config/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/renovate-config): disable separateMinorPatch

- .github/labeler.yml
- .github/workflows/labeler.yml
- packages/renovate-config/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: add labeler.yml

- .github/workflows/lock.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: add lock.yml

- .github/workflows/autoupdate.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: add autoupdate.yml

- packages/ng-excel-builder/src/excel-builder.service.ts
-   [] Tests for the changes have been added (for bug fixes / features)
-   [] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/ng-excel-builder): changed format

- packages/common/integration/tests/number/number.spec.ts
- packages/common/integration/tests/pipes/number-format.spec.ts
-   [] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: tests fixed
```
```
[ ] Yes
[x] No
```
> fix(common): changed tests that brakes on Windows

- packages/common/docs/pipes.md
- packages/common/integration/tests/pipes/includes-pipe.spec.ts
- packages/common/pipes/src/includes/includes-pipe.module.ts
- packages/common/pipes/src/includes/includes.pipe.ts
- packages/common/pipes/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add Includes pipe

- packages/common/class-transformer/src/public_api.ts
- packages/common/class-transformer/src/transform-date-to-format.ts
- packages/common/docs/class-transformer.md
- packages/common/integration/tests/class-transformer/class-transformer.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat: add transform-date-to-format

- packages/stream/integration/tests/browser/jwt.spec.ts
- packages/stream/jwt/src/decode-jwt.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(@angular-core/jwt): change decode-jwt signature

- packages/common/array/src/unique-array-of.ts
- packages/common/class-transformer/src/transform-to-class.ts
- packages/common/class-transformer/src/transform-to-pretty-format.ts
- packages/common/coercion/package.json
- packages/common/coercion/src/coerce-boolean.ts
- packages/common/coercion/src/public_api.ts
- packages/common/date/src/shift-date/shift-date.ts
- packages/common/date/src/to-format-date-time.ts
- packages/common/date/src/to-format.ts
- packages/common/date/src/to-iso-string.ts
- packages/common/date/src/to-pretty-format.ts
- packages/common/date/src/to-timestamp.ts
- packages/common/decorators/src/attribute-boolean.ts
- packages/common/integration/tests/coercion/coercion.spec.ts
- packages/common/typings/src/input-boolean.ts
- packages/eslint-config/index.js
- packages/tooltip/src/tooltip.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: refactor before integrate strict-boolean-expressions

- packages/ng-table-builder/src/table-builder.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(ng-table-builder): fixed bug with rows rendering

- packages/common/docs/utils.md
- packages/common/integration/tests/utils/utils.spec.ts
- packages/common/typings/src/empty-value.ts
- packages/common/utils/src/fallback-if-empty.ts
- packages/common/utils/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/common): add fallbackIfEmpty function

- packages/ng-table-builder/src/table-builder.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(ng-table-buider): removed last changes

- packages/common/date/src/to-iso-string.ts
- packages/common/integration/tests/date/serial-date.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(@angular-ru/common): prevent invalid date time

- .github/workflows/autoupdate.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: update autoupdate.yml

- packages/common/array/src/update-array.ts
- packages/common/integration/tests/array/update-array.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/common): support nullable values when update array

- packages/ng-table-builder/src/styles/scrollbar.scss
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(@angular-ru/ng-table-builder): fix scrollbar styles

- packages/ng-table-builder/integration/tests/components/table-builder.component.spec.ts
- packages/ng-table-builder/integration/tests/helpers/utils/mocks-generator.ts
- packages/ng-table-builder/integration/tests/samples/lifecycle/lifecycle.spec.ts
- packages/ng-table-builder/src/services/filterable/filter.worker.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(@angular-ru/ng-table-builder): fix null values filter errors

- packages/ng-table-builder/src/config/table-global-options.ts
- packages/ng-table-builder/src/table-builder.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(ng-table-builder): added update view on changes

- packages/commitlint-config/index.js
- packages/commitlint-config/package.json
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[x] No
```
> ci: commitlint head-max-length 100

- packages/ng-excel-builder/package.json
- packages/ng-excel-builder/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(ng-excel-builder): add EntriesKeys to public api

- packages/common/docs/pipes.md
- packages/common/pipes/src/declination-of-number/declination-of-number-pipe.module.ts
- packages/common/pipes/src/declination-of-number/declination-of-number.pipe.ts
- packages/common/pipes/src/public_api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
>  feat(@angular-ru/common): add DeclinationOfNumberPipe

- packages/common/zone.js/src/_noop.ts
- packages/common/zone.js/src/public_api.ts
- packages/common/zone.js/src/unpatch-events.ts
- packages/common/zone.js/unpatch-zone/src/unpatch-events.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/common): remove deprecated utils from */zone.js

- packages/http/decorators/src/internal/ensure-descriptor-by-type.ts
- packages/http/decorators/src/internal/mutate-path-by-path-variables.ts
- packages/http/integration/tests/decorators/without-decorators.spec.ts
- packages/http/src/configs/data-request-options.config.ts
- packages/http/typings/src/interfaces/data-client-request-options.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/http): support passing explicit variables in path

- packages/common/utils/src/try-parse-json.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/common): improved tryParseJson

- BREAKING_CHANGES.md
- packages/common/docs/utils.md
- packages/common/integration/tests/utils/utils.spec.ts
- packages/common/typings/src/empty-value.ts
- packages/common/utils/src/check-value-is-empty.ts
- packages/ng-excel-builder/src/excel-builder.service.ts
- packages/ng-table-builder/src/services/sortable/sort.worker.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/common): remove 'null' as empty value

- packages/common/docs/object.md
- packages/common/integration/tests/object/object.spec.ts
- packages/common/object/src/map-object.ts
- packages/common/object/src/public_api.ts
- packages/common/object/src/shallow-map-object.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/common): add mapObject function

- packages/ng-table-builder/src/abstract-table-builder-api.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(@angular-ru/ng-table-builder): set async stub for trigger onChanges

- packages/common/array/src/unique-array-of.ts
- packages/common/number/src/number-format/number-format.ts
- packages/common/pipes/src/deep-path/deep-path.pipe.ts
- packages/common/pipes/src/includes/includes.pipe.ts
- packages/eslint-config/index.js
- packages/flex-layout/src/directives/flex-bottom-indent.directive.ts
- packages/http/src/services/limit-concurency.service.ts
- packages/logger/src/logger.injector.ts
- packages/ng-excel-builder/setup-jest.ts
- packages/ng-table-builder/setup-jest.ts
- packages/websocket/setup-jest.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(@angular-ru/eslint-config): required new line after import

- packages/common/integration/tests/nodejs/ts-utils.spec.ts
- packages/common/tsconfig.app.json
- packages/common/tsconfig.base.json
- packages/common/tsconfig.lib.json
- packages/common/tsconfig.spec.json
- packages/flex-layout/tsconfig.app.json
- packages/http/tsconfig.app.json
- packages/http/tsconfig.lib.json
- packages/logger/tsconfig.app.json
- packages/logger/tsconfig.lib.json
- packages/ng-excel-builder/tsconfig.app.json
- packages/ng-excel-builder/tsconfig.lib.json
- packages/ng-table-builder/tsconfig.app.json
- packages/ng-table-builder/tsconfig.lib.json
- packages/stream/tsconfig.app.json
- packages/stream/tsconfig.lib.json
- packages/tooltip/tsconfig.app.json
- packages/tooltip/tsconfig.lib.json
- packages/websocket/tsconfig.lib.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: use es2015 by default

- .prettierignore
- lerna.json
- packages/build-tools/package.json
- packages/commitlint-config/package.json
- packages/common/package.json
- packages/eslint-config/package.json
- packages/eslint-plugin/package.json
- packages/flex-layout/package.json
- packages/http/package.json
- packages/jest-utils/package.json
- packages/logger/package.json
- packages/ng-excel-builder/package.json
- packages/ng-table-builder/integration/app/src/samples/sample-fourteen/not-found.component.ts
- packages/ng-table-builder/integration/tests/helpers/mocks/simple-mock.component.ts
- packages/ng-table-builder/integration/tests/helpers/mocks/template-mock.component.ts
- packages/ng-table-builder/package.json
- packages/prettier-config/package.json
- packages/renovate-config/package.json
- packages/stream/package.json
- packages/tooltip/package.json
- packages/tsconfig/package.json
- packages/websocket/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: force bump versions

- packages/ng-table-builder/src/table-builder.component.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(@angular-ru/ng-table-builder): fix styles of expand button

- packages/ng-table-builder/src/abstract-table-builder-api.directive.ts
- packages/ng-table-builder/src/interfaces/table-builder.external.ts
- packages/ng-table-builder/src/table-builder.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/ng-table-builder): expand state to TableUpdateSchema

- .github/workflows/workflow.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: remove deploy app

- packages/ng-table-builder/src/table-builder.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/ng-table-builder): add public method filterBySubstring

- packages/renovate-config/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(@angular-ru/renovate-config): set masterIssueApproval as false

- packages/ng-excel-builder/integration/tests/excel.service.spec.ts
- packages/ng-excel-builder/integration/tests/helpers/file-suites/test-8-auto-width.xls
- packages/ng-excel-builder/src/domain/excel-worksheet.ts
- packages/ng-excel-builder/src/excel-builder.service.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(@angular-ru/ng-excel-builder): added generalColumnParameters

- lerna.json
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: set independent version in lerna.json

- .editorconfig
- .github/labeler.yml
- packages/eslint/README.md
- packages/jest/README.md
- packages/prettier/README.md
- packages/renovate/README.md
- renovate.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: update

- .github/CODEOWNERS
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: renovate-approve support

- packages/commitlint/index.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: support chore prefix

- packages/dev-dependencies/package.json
- yarn.lock
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: add standard-version

- packages/ng-table-builder/integration/tests/samples/lifecycle/lifecycle.spec.ts
- packages/ng-table-builder/src/pipes/map-to-table-entries.pipe.ts
- packages/ng-table-builder/src/pipes/table-selected-items.pipe.ts
- packages/ng-table-builder/src/public_api.ts
- packages/ng-table-builder/src/services/selection/selection.ts
- packages/ng-table-builder/src/table-builder.component.ts
- packages/ng-table-builder/src/table-builder.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat: new selected items pipe (based on array)

- lerna.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build(cdk): update lerna.json

- packages/ngxs/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(ngxs): update README.md

- packages/cdk/array/src/update-array.ts
- packages/cdk/docs/array.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(cdk): improve signature for updateArray function

- .github/workflows/build.yml
- packages/cdk/integration/tests/jest/array/update-array.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: remove build & temporary test & fix tests for updateArray

- packages/cdk/array/src/update-array.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(cdk): fix updateArray id type

- commitlint.config.js
- dev-infra/renovate/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(renovate): add new rules

- dev-infra/renovate/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(renovate): remove all slug

- dev-infra/renovate/README.md
- dev-infra/renovate/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(renovate): rewrite rules for exclude expected groups

- dev-infra/renovate/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(renovate): lift to the top common rule

- dev-infra/renovate/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(renovate): rename groups for correct messages

- packages/cdk/docs/validators.md
- packages/cdk/integration/tests/jest/validators/required-some-value-validator.spec.ts
- packages/cdk/validators/src/public_api.ts
- packages/cdk/validators/src/required-some-value.validator.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x ] No
```
> feat: added requiredSomeValueValidator

- .gitignore
- dev-infra/jest/package.json
- dev-infra/jest/src/constants/configurations.ts
- dev-infra/jest/src/utils/create-ts-jest-config.ts
- yarn.lock
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(jest): add default reporters

- .github/autorebase.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: set dry-run for autoupdate

- .github/labeler.yml
- .github/workflows/labeler.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: remove redundant

- packages/cdk/docs/utils.md
- packages/cdk/integration/tests/jest/utils/utils.spec.ts
- packages/cdk/utils/src/is-boolean.ts
- packages/cdk/utils/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cdk): add 'isBoolean' utility

- .github/workflows/assign-project.yml
- .github/workflows/autorebase.yml
- .github/workflows/build.yml
- .github/workflows/labeler.yml
- .github/workflows/skip-workflow.yml
- dev-infra/commitlint/package.json
- dev-infra/dev-dependencies/package.json
- dev-infra/eslint-config-enterprise/package.json
- dev-infra/eslint-plugin-enterprise/package.json
- dev-infra/jest/package.json
- dev-infra/prettier/package.json
- dev-infra/renovate/package.json
- dev-infra/typescript/package.json
- packages/cdk/package.json
- packages/ngxs/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: check bot access

- packages/cdk/class-transformer/src/public_api.ts
- packages/cdk/class-transformer/src/transform-to-boolean.ts
- packages/cdk/class-transformer/src/transform-to-nullable-boolean.ts
- packages/cdk/docs/class-transformer.md
- packages/cdk/integration/tests/jest/class-transformer/class-transformer.spec.ts
- packages/cdk/integration/tests/jest/class-transformer/transform-to-boolean.spec.ts
- packages/cdk/integration/tests/jest/class-transformer/transform-to-nullable-boolean.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat: added util transformToNullableBoolean

- packages/cdk/virtual-table/src/table-builder.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cdk): fix not-found display condition

- packages/cdk/docs/utils.md
- packages/cdk/integration/tests/jest/regexp/regexp-constants.spec.ts
- packages/cdk/integration/tests/jest/utils/replace-units.spec.ts
- packages/cdk/regexp/src/constants.ts
- packages/cdk/regexp/src/public_api.ts
- packages/cdk/utils/src/public_api.ts
- packages/cdk/utils/src/replace-units/properties.ts
- packages/cdk/utils/src/replace-units/replace-units.ts
- packages/cdk/utils/src/replace-units/types.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat: added util replace-with-numbers

- packages/cdk/array/src/by-property-value.ts
- packages/cdk/array/src/public_api.ts
- packages/cdk/docs/array.md
- packages/cdk/integration/tests/jest/array/by-property-value.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cdk): add byPropertyValue utility

- packages/cdk/virtual-table/src/abstract-table-builder-api.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cdk): selectedItems refactor

- dev-infra/eslint-config-enterprise/README.md
- dev-infra/eslint-config-enterprise/package.json
- dev-infra/eslint-config-enterprise/scope/spell-check.js
- yarn.lock
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(eslint-config-enterprise): make spellchecker configurable on client

- packages/cdk/directives/src/trim-input/trim-input.directive.ts
- packages/cdk/docs/directives.md
- packages/cdk/integration/tests/jest/directives/trim/disabled-trim-input.spec.ts
```
[ ] Bugfix
[x] Feature
```
trim directive can't be disabled by input parameter
Issue Number: 1137
trim directive can be disabled by input parameter
```
[ ] Yes
[x] No
```
> trim directive: disabling input 

- packages/cdk/directives/src/initial-focus/initial-focus.directive.ts
- packages/cdk/docs/directives.md
- packages/cdk/integration/tests/jest/directives/initial-focus.spec.ts
```
[ ] Bugfix
[x] Feature
```
initial focus directive can't be disabled with input parameter
initial focus directive can be disabled with input parameter
```
[ ] Yes
[x] No
```
> feat: initial focus disabling

- packages/cdk/docs/utils.md
- packages/cdk/integration/tests/jest/table-utils/table-clipboard.spec.ts
- packages/cdk/table-utils/src/table-clipboard/table-clipboard.service.ts
- packages/cdk/utils/src/copy-html.ts
- packages/cdk/utils/src/copy-string.ts
- packages/cdk/utils/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(cdk): add `copyHtml` feature, rename `copyBuffer`

- packages/cdk/docs/validators.md
- packages/cdk/integration/tests/jest/validators/empty-validator.spec.ts
- packages/cdk/integration/tests/jest/validators/long-validator.spec.ts
- packages/cdk/validators/src/empty.validator.ts
- packages/cdk/validators/src/long.validator.ts
- packages/cdk/validators/src/public_api.ts
-   [ x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
-   [ x] Tests for the changes have been added (for bug fixes / features)
-   [ x] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ x] Feature
```
```
[ ] Yes
[ x] No
```
> feat: added util longValidator

- .github/actions/autopush/action.yml
- .github/actions/git/action.yml
- .github/actions/nodejs/action.yml
- .github/workflows/build.yml
- .github/workflows/lint.yml
- dev-infra/eslint-plugin-enterprise/package.json
- package.json
- packages/ngxs/decorators/src/computed/computed.ts
- packages/ngxs/integration/tests/common-extensions/computed-observable.spec.ts
- packages/ngxs/storage/src/utils/expose-engine.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: add lint code

- .github/workflows/autorebase.yml
- .github/workflows/build.yml
- .github/workflows/integrations.yml
- .github/workflows/labeler.yml
- .github/workflows/lint.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: decomposition actions

- .github/actions/autopush/action.yml
- .github/actions/git/action.yml
- .github/workflows/labeler.yml
- .github/workflows/test.yml
- dev-infra/commitlint/package.json
- dev-infra/dev-dependencies/package.json
- dev-infra/eslint-config-enterprise/package.json
- dev-infra/eslint-plugin-enterprise/package.json
- dev-infra/jest/package.json
- dev-infra/prettier/package.json
- dev-infra/renovate/package.json
- dev-infra/typescript/package.json
- packages/cdk/package.json
- packages/ngxs/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: decomposition actions (#1196) (#1198)

- packages/ngxs/repositories/src/ngxs-data-entity-collections/ngxs-data-entity-collections.repository.ts
> Only remove all entities from the state

- .github/workflows/test.yml
- libs/cdk/jest.config.js
- libs/cdk/project.json
- libs/cdk/tests/date/shift-date.spec.ts
- libs/eslint-config-enterprise/jest.config.js
- libs/eslint-config-enterprise/project.json
- libs/eslint-plugin-enterprise/project.json
- libs/jest/project.json
- libs/jest/src/interfaces/jest-config-options.ts
- libs/jest/src/utils/create-ts-jest-config.ts
- nx.json
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
[x] CI related changes
```
```
[ ] Yes
[ ] No
```
> build: mark target's dependencies in global config

- libs/cdk/virtual-table/src/styles/common.scss
-   [ x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
```
[ x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ x] No
```
> fix: changed table scroll

- .github/workflows/release.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: provide npm token via echo

- .github/workflows/release.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: provide npm registry directly to .npmrc

- .github/workflows/release.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: run nx outside yarn environment

- libs/cdk/tests/virtual-table/components/table-builder.component.spec.ts
- libs/cdk/virtual-table/src/services/filterable/filter.worker.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(cdk): support numbers and booleans in table filter

- libs/cdk/string/src/trim.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(cdk): correct `trim` function signature

- RELEASE_NOTES.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: update RELEASE_NOTE

- apps/virtual-table-demo/src/samples/sample-fourteen/context-menu-sample/context-menu-sample.component.html
- apps/virtual-table-demo/src/samples/sample-fourteen/context-menu-sample/context-menu-sample.component.ts
- apps/virtual-table-demo/src/samples/sample-fourteen/sample-fourteen.module.ts
- libs/cdk/pipes/src/is-filled/is-filled-pipe.module.ts
- libs/cdk/pipes/src/is-filled/is-filled.pipe.ts
- libs/cdk/pipes/src/public_api.ts
- libs/cdk/tests/virtual-table/components/table-builder.component.spec.ts
- libs/cdk/virtual-table/src/components/table-thead/table-thead.component.html
- libs/cdk/virtual-table/src/services/filterable/filter.worker.ts
- libs/cdk/virtual-table/src/services/filterable/table-filter-type.ts
- libs/cdk/virtual-table/src/table-builder.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(cdk): table filter type IS_FILLED

- libs/cdk/project.json
BREAKING CHANGES: v13
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: publishing fix

- libs/cdk/package.json
- libs/commitlint/package.json
- libs/dev-dependencies/package.json
- libs/eslint-config-enterprise/package.json
- libs/eslint-plugin-enterprise/package.json
- libs/jest/package.json
- libs/ngxs/package.json
- libs/prettier/package.json
- libs/renovate/package.json
- libs/typescript/package.json
- package-lock.json
BREAKING CHANGES: Angular 13
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> BREAKING CHANGE: Angular 13

- libs/cdk/virtual-table/src/abstract-table-builder-api.directive.ts
- libs/cdk/virtual-table/src/table-builder.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat: added virtual table feature to be used as non-virtual

- package-lock.json
```
[ ] Bugfix
[ ] Feature
[X] CI related changes
```
```
[ ] Yes
[ ] No
```
> build: change package-lock

- libs/commitlint/project.json
- libs/dev-dependencies/project.json
- libs/eslint-config-enterprise/project.json
- libs/eslint-plugin-enterprise/project.json
- libs/jest/project.json
- libs/prettier/project.json
- libs/renovate/project.json
- libs/typescript/project.json
-   [ x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[X] No
```
> ci: fix release

- libs/cdk/virtual-table/src/components/table-cell/table-cell.component.ts
```
[x] Bugfix
[ ] Feature
```
Tooltip does not disappear in some cases.
Changed the behavior when defining the overflowTooltip option. Added more explicit validation conditions for creating and deleting a tooltip.
``` …
```
> fix: virtual-table cell overflow tooltip behaviour

- .github/workflows/release.yml
- apps/virtual-table-demo/project.json
- libs/cdk/virtual-table/src/components/ngx-filter-viewer/ngx-filter-viewer.component.ts
- libs/cdk/virtual-table/src/services/filterable/filter.worker.ts
-   [X] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
```
[x] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[x] No
```
> fix: virtual table contain several values fix

- libs/ngxs/decorators/src/persistence/persistence.ts
- libs/ngxs/internals/src/public_api.ts
- libs/ngxs/internals/src/storage/init-storage.ts
- libs/ngxs/storage/src/ngxs-data-storage-plugin.service.ts
- libs/ngxs/tests/storage-extensions/storage.spec.ts
- libs/ngxs/typings/src/storage/storage.ts
```
[*] Bugfix
[ ] Feature
```
@Persistence decorator not working in feature module
Issue Number: 862
@Persistence decorator works in feature module
```
[ ] Yes
[*] No
```
> fix: persistence decorator in feature module fixed

- apps/virtual-table-demo/src/samples/sample-eleven/sample-eleven.component.html
- apps/virtual-table-demo/src/samples/sample-eleven/sample-eleven.component.ts
- libs/cdk/virtual-table/src/components/table-thead/table-thead.component.ts
- libs/cdk/virtual-table/src/table-builder.component.html
- libs/cdk/virtual-table/src/table-builder.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix: add column id info to context menu in table header

- libs/cdk/excel/src/domain/column-parameters.ts
- libs/cdk/excel/src/domain/excel-type.ts
- libs/cdk/excel/src/excel-builder.service.ts
- libs/cdk/tests/excel/file-suites/test-1-simple.xls
- libs/cdk/tests/excel/file-suites/test-2-by-keys.xls
- libs/cdk/tests/excel/file-suites/test-3-exclude-keys.xls
- libs/cdk/tests/excel/file-suites/test-4-options.xls
- libs/cdk/tests/excel/file-suites/test-5-translate.xls
- libs/cdk/tests/excel/file-suites/test-6-auto-width.xls
- libs/cdk/tests/excel/file-suites/test-7-auto-width-translate.xls
- libs/cdk/tests/excel/file-suites/test-8-auto-width.xls
- libs/cdk/virtual-table/src/components/ngx-column/ngx-column.component.ts
- libs/cdk/virtual-table/src/interfaces/table-builder.external.ts
- libs/cdk/virtual-table/src/services/template-parser/template-parser.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: add datetime column excel export to table

- libs/cdk/excel/src/public_api.ts
- libs/cdk/virtual-table/src/components/ngx-column/ngx-column.component.ts
- libs/cdk/virtual-table/src/interfaces/table-builder.external.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: add excel type to column schema

- libs/cdk/excel/src/excel-builder.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: remove usage of imported function in webworker

- .github/workflows/release.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: add npm whoami to release yml

- libs/eslint-config-enterprise/package.json
- package-lock.json
Update to fix issue: https://github.com/lo1tuma/eslint-plugin-mocha/issues/322
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: update eslint-plugin-mocha to version 10.1.0

- libs/cdk/virtual-table/src/services/filterable/filter.worker.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: virtual-table add array support to isFilled

- libs/cdk/tsconfig.lib.json
- libs/ngxs/tsconfig.lib.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat: enable preserveConstEnums for buildable libs (#1387)

- libs/cdk/tsconfig.lib.json
- libs/ngxs/tsconfig.lib.json
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1409 
```
[ ] Yes
[ ] No
```
Closes #1409
> fix: use compilationMode `partial` for libraries #1409

- apps/cdk-demo/project.json
- apps/excel-demo/project.json
- apps/flex-layout-demo/project.json
- apps/http-demo/project.json
- apps/logger-demo/project.json
- apps/ngxs-demo/project.json
- apps/tooltip-demo/project.json
- apps/virtual-table-demo/project.json
-   [x ] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Demo projects are served using production configuration by default
Demo projects are served using development configuration by default 
```
[ ] Yes
[ x] No
```
> fix: change default configuration for serving demo projects

- libs/cdk/tsconfig.spec.json
- libs/cdk/utils/src/copy-html.ts
- libs/jest/tsconfig.spec.json
- libs/ngxs/tsconfig.spec.json
- libs/type-declarations/README.md
- libs/type-declarations/index.d.ts
- libs/type-declarations/package.json
- libs/type-declarations/project.json
- libs/typescript/tsconfig.json
- tsconfig.json
- workspace.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
Closes #1487
> feat: add `type-declarations` lib with `nil` type (#1487)

- libs/cdk/date/src/date-suggestion/strategies/date-suggestion-calendar-week.strategy.ts
- libs/cdk/date/src/date-suggestion/tokens/first-day-of-week.ts
- libs/cdk/date/src/public_api.ts
- libs/cdk/directives/src/convert-case/convert-case.directive.ts
- libs/cdk/package.json
- libs/cdk/tests/date/date-suggestion-custom.spec.ts
- libs/cdk/tests/date/date-suggestion.spec.ts
- libs/cdk/tests/directives/filter/filter-config.spec.ts
- libs/cdk/tests/directives/filter/filter-dynamic.spec.ts
- libs/cdk/tests/directives/filter/filter-form.spec.ts
- libs/cdk/tests/directives/filter/filter-input.spec.ts
- libs/cdk/tests/directives/filter/filter-simple-input.spec.ts
- libs/cdk/tests/directives/initial-focus.spec.ts
- libs/cdk/tests/directives/trim/disabled-trim-input.spec.ts
- libs/cdk/tests/directives/trim/dynamic-trim-input.spec.ts
- libs/cdk/tests/directives/trim/ng-model.spec.ts
- libs/cdk/tests/directives/trim/trim-input.spec.ts
- libs/cdk/tests/pipes/mutable-pipe.spec.ts
- libs/cdk/tests/virtual-table/components/selection-mock.component.spec.ts
- libs/cdk/tests/virtual-table/components/table-builder.component.spec.ts
- libs/cdk/virtual-table/src/components/ngx-header/ngx-header.component.html
- libs/cdk/virtual-table/src/table-builder.module.ts
```
[ ] Bugfix
[x] Feature
```
`cdk` library depends on `@angular/material`.
Issue Number: #1518
`cdk` library no longer depends on `@angular/material`.
```
[x] Yes
[ ] No
```
> Remove `@angular/material` dependency from `cdk` library

- libs/cdk/http/typings/src/interfaces/data-client-request-options.ts
- libs/cdk/http/utils/src/get-http-params.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: allow to provide HttpParams in DataClientRequestOptions (#1522)

- libs/ngxs/decorators/data-action/data-action.ts
- libs/ngxs/internals/services/ngxs-data-factory.service.ts
- libs/ngxs/internals/services/ngxs-data-injector.service.ts
- libs/ngxs/internals/utils/state-context/create-context.ts
- libs/ngxs/package.json
- libs/ngxs/storage/utils/rehydrate.ts
- libs/ngxs/testing/platform/ngxs-data-testing.module.ts
- libs/ngxs/testing/platform/ngxs-platform.ts
- libs/ngxs/tests/common-extensions/action-decorator.spec.ts
- libs/ngxs/tests/common-extensions/state-context.spec.ts
- libs/ngxs/tests/entity/primary-key-or-unique-id.spec.ts
- libs/ngxs/tests/inheritance-extensions/children.spec.ts
- libs/ngxs/typings/common/data-state-class.ts
- libs/ngxs/typings/common/mapped-state.ts
- libs/ngxs/typings/common/mapped-store.ts
- libs/ngxs/typings/common/state-factory.ts
- libs/ngxs/typings/index.ts
- package-lock.json
- package.json
> fix(ngxs): upgrade to NGXS 18.1.3

- libs/ngxs/internals/services/ngxs-data-factory.service.ts
- libs/ngxs/package.json
- libs/ngxs/typings/common/state-factory.ts
- package-lock.json
- package.json
Throws "access to undefined property" error with NGXS `18.1.6`
Works with NGXS `18.1.6`
> fix(ngxs): upgrade to NGXS 18.1.6
